apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi  # ขนาดพื้นที่จริงที่คุณเตรียมไว้
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres" # พาธบนเครื่อง Node ที่จะใช้เก็บข้อมูลจริง