apiVersion: v1
kind: Secret
metadata:
  name: sut-attendance-secret
  namespace: default
type: Opaque
data:
  # รหัสผ่านสำหรับ PostgreSQL (Base64 ของ 'sut_pass')
  db-password: c3V0X3Bhc3M=
  
  # คีย์สำหรับ Gen Token/Login (Base64 ของ 'sut_super_secret_key_2026')
  jwt-secret: c3V0X3N1cGVyX3NlY3JldF9rZXlfMjAyNg==