apiVersion: v1
kind: Service
metadata:
  name: sut-postgres-service # 👈 ชื่อนี้สำคัญมาก! Backend จะใช้ชื่อนี้แทน IP Address
  namespace: default
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432