Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "sut-attendance-server"
  config.vm.boot_timeout = 600  # รอนานขึ้นเป็น 10 นาที
  
  config.vm.network "private_network", ip: "192.168.56.10"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "sut-attendance-server"
    vb.cpus   = 2
    vb.memory = 2048
    vb.gui    = true  # เปิดหน้าจอ VM เพื่อดูว่าบูทถึงไหน
  end
end